// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clicktracker.proto

package com.digitald4.clicktracker.proto;

public final class ClickTrackerProtos {
  private ClickTrackerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClickOrBuilder extends
      // @@protoc_insertion_point(interface_extends:budget.Click)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string url = 2;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>int64 recorded = 3;</code>
     */
    long getRecorded();

    /**
     * <code>string ip_address = 4;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>string ip_address = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>string accept_language = 5;</code>
     */
    java.lang.String getAcceptLanguage();
    /**
     * <code>string accept_language = 5;</code>
     */
    com.google.protobuf.ByteString
        getAcceptLanguageBytes();

    /**
     * <code>string request_language = 6;</code>
     */
    java.lang.String getRequestLanguage();
    /**
     * <code>string request_language = 6;</code>
     */
    com.google.protobuf.ByteString
        getRequestLanguageBytes();

    /**
     * <code>string redirect_url = 7;</code>
     */
    java.lang.String getRedirectUrl();
    /**
     * <code>string redirect_url = 7;</code>
     */
    com.google.protobuf.ByteString
        getRedirectUrlBytes();
  }
  /**
   * Protobuf type {@code budget.Click}
   */
  public  static final class Click extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:budget.Click)
      ClickOrBuilder {
    // Use Click.newBuilder() to construct.
    private Click(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Click() {
      id_ = 0;
      url_ = "";
      recorded_ = 0L;
      ipAddress_ = "";
      acceptLanguage_ = "";
      requestLanguage_ = "";
      redirectUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Click(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 24: {

              recorded_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ipAddress_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              acceptLanguage_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              requestLanguage_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              redirectUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.clicktracker.proto.ClickTrackerProtos.internal_static_budget_Click_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.clicktracker.proto.ClickTrackerProtos.internal_static_budget_Click_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.class, com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 2;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDED_FIELD_NUMBER = 3;
    private long recorded_;
    /**
     * <code>int64 recorded = 3;</code>
     */
    public long getRecorded() {
      return recorded_;
    }

    public static final int IP_ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object ipAddress_;
    /**
     * <code>string ip_address = 4;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string ip_address = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCEPT_LANGUAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object acceptLanguage_;
    /**
     * <code>string accept_language = 5;</code>
     */
    public java.lang.String getAcceptLanguage() {
      java.lang.Object ref = acceptLanguage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acceptLanguage_ = s;
        return s;
      }
    }
    /**
     * <code>string accept_language = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAcceptLanguageBytes() {
      java.lang.Object ref = acceptLanguage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_LANGUAGE_FIELD_NUMBER = 6;
    private volatile java.lang.Object requestLanguage_;
    /**
     * <code>string request_language = 6;</code>
     */
    public java.lang.String getRequestLanguage() {
      java.lang.Object ref = requestLanguage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestLanguage_ = s;
        return s;
      }
    }
    /**
     * <code>string request_language = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRequestLanguageBytes() {
      java.lang.Object ref = requestLanguage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REDIRECT_URL_FIELD_NUMBER = 7;
    private volatile java.lang.Object redirectUrl_;
    /**
     * <code>string redirect_url = 7;</code>
     */
    public java.lang.String getRedirectUrl() {
      java.lang.Object ref = redirectUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redirectUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string redirect_url = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRedirectUrlBytes() {
      java.lang.Object ref = redirectUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
      if (recorded_ != 0L) {
        output.writeInt64(3, recorded_);
      }
      if (!getIpAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ipAddress_);
      }
      if (!getAcceptLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, acceptLanguage_);
      }
      if (!getRequestLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requestLanguage_);
      }
      if (!getRedirectUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, redirectUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      if (recorded_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, recorded_);
      }
      if (!getIpAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ipAddress_);
      }
      if (!getAcceptLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, acceptLanguage_);
      }
      if (!getRequestLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requestLanguage_);
      }
      if (!getRedirectUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, redirectUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.digitald4.clicktracker.proto.ClickTrackerProtos.Click)) {
        return super.equals(obj);
      }
      com.digitald4.clicktracker.proto.ClickTrackerProtos.Click other = (com.digitald4.clicktracker.proto.ClickTrackerProtos.Click) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && (getRecorded()
          == other.getRecorded());
      result = result && getIpAddress()
          .equals(other.getIpAddress());
      result = result && getAcceptLanguage()
          .equals(other.getAcceptLanguage());
      result = result && getRequestLanguage()
          .equals(other.getRequestLanguage());
      result = result && getRedirectUrl()
          .equals(other.getRedirectUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + RECORDED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRecorded());
      hash = (37 * hash) + IP_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress().hashCode();
      hash = (37 * hash) + ACCEPT_LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAcceptLanguage().hashCode();
      hash = (37 * hash) + REQUEST_LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestLanguage().hashCode();
      hash = (37 * hash) + REDIRECT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getRedirectUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.clicktracker.proto.ClickTrackerProtos.Click prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code budget.Click}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:budget.Click)
        com.digitald4.clicktracker.proto.ClickTrackerProtos.ClickOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.clicktracker.proto.ClickTrackerProtos.internal_static_budget_Click_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.clicktracker.proto.ClickTrackerProtos.internal_static_budget_Click_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.class, com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.Builder.class);
      }

      // Construct using com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        url_ = "";

        recorded_ = 0L;

        ipAddress_ = "";

        acceptLanguage_ = "";

        requestLanguage_ = "";

        redirectUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.clicktracker.proto.ClickTrackerProtos.internal_static_budget_Click_descriptor;
      }

      public com.digitald4.clicktracker.proto.ClickTrackerProtos.Click getDefaultInstanceForType() {
        return com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.getDefaultInstance();
      }

      public com.digitald4.clicktracker.proto.ClickTrackerProtos.Click build() {
        com.digitald4.clicktracker.proto.ClickTrackerProtos.Click result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.clicktracker.proto.ClickTrackerProtos.Click buildPartial() {
        com.digitald4.clicktracker.proto.ClickTrackerProtos.Click result = new com.digitald4.clicktracker.proto.ClickTrackerProtos.Click(this);
        result.id_ = id_;
        result.url_ = url_;
        result.recorded_ = recorded_;
        result.ipAddress_ = ipAddress_;
        result.acceptLanguage_ = acceptLanguage_;
        result.requestLanguage_ = requestLanguage_;
        result.redirectUrl_ = redirectUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.clicktracker.proto.ClickTrackerProtos.Click) {
          return mergeFrom((com.digitald4.clicktracker.proto.ClickTrackerProtos.Click)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.clicktracker.proto.ClickTrackerProtos.Click other) {
        if (other == com.digitald4.clicktracker.proto.ClickTrackerProtos.Click.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getRecorded() != 0L) {
          setRecorded(other.getRecorded());
        }
        if (!other.getIpAddress().isEmpty()) {
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        if (!other.getAcceptLanguage().isEmpty()) {
          acceptLanguage_ = other.acceptLanguage_;
          onChanged();
        }
        if (!other.getRequestLanguage().isEmpty()) {
          requestLanguage_ = other.requestLanguage_;
          onChanged();
        }
        if (!other.getRedirectUrl().isEmpty()) {
          redirectUrl_ = other.redirectUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.clicktracker.proto.ClickTrackerProtos.Click parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.clicktracker.proto.ClickTrackerProtos.Click) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 2;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private long recorded_ ;
      /**
       * <code>int64 recorded = 3;</code>
       */
      public long getRecorded() {
        return recorded_;
      }
      /**
       * <code>int64 recorded = 3;</code>
       */
      public Builder setRecorded(long value) {
        
        recorded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 recorded = 3;</code>
       */
      public Builder clearRecorded() {
        
        recorded_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ipAddress_ = "";
      /**
       * <code>string ip_address = 4;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip_address = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip_address = 4;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip_address = 4;</code>
       */
      public Builder clearIpAddress() {
        
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string ip_address = 4;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object acceptLanguage_ = "";
      /**
       * <code>string accept_language = 5;</code>
       */
      public java.lang.String getAcceptLanguage() {
        java.lang.Object ref = acceptLanguage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          acceptLanguage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accept_language = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAcceptLanguageBytes() {
        java.lang.Object ref = acceptLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acceptLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accept_language = 5;</code>
       */
      public Builder setAcceptLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        acceptLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accept_language = 5;</code>
       */
      public Builder clearAcceptLanguage() {
        
        acceptLanguage_ = getDefaultInstance().getAcceptLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string accept_language = 5;</code>
       */
      public Builder setAcceptLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        acceptLanguage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestLanguage_ = "";
      /**
       * <code>string request_language = 6;</code>
       */
      public java.lang.String getRequestLanguage() {
        java.lang.Object ref = requestLanguage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestLanguage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string request_language = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRequestLanguageBytes() {
        java.lang.Object ref = requestLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string request_language = 6;</code>
       */
      public Builder setRequestLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string request_language = 6;</code>
       */
      public Builder clearRequestLanguage() {
        
        requestLanguage_ = getDefaultInstance().getRequestLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string request_language = 6;</code>
       */
      public Builder setRequestLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestLanguage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object redirectUrl_ = "";
      /**
       * <code>string redirect_url = 7;</code>
       */
      public java.lang.String getRedirectUrl() {
        java.lang.Object ref = redirectUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          redirectUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string redirect_url = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRedirectUrlBytes() {
        java.lang.Object ref = redirectUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string redirect_url = 7;</code>
       */
      public Builder setRedirectUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        redirectUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string redirect_url = 7;</code>
       */
      public Builder clearRedirectUrl() {
        
        redirectUrl_ = getDefaultInstance().getRedirectUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string redirect_url = 7;</code>
       */
      public Builder setRedirectUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        redirectUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:budget.Click)
    }

    // @@protoc_insertion_point(class_scope:budget.Click)
    private static final com.digitald4.clicktracker.proto.ClickTrackerProtos.Click DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.clicktracker.proto.ClickTrackerProtos.Click();
    }

    public static com.digitald4.clicktracker.proto.ClickTrackerProtos.Click getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Click>
        PARSER = new com.google.protobuf.AbstractParser<Click>() {
      public Click parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Click(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Click> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Click> getParserForType() {
      return PARSER;
    }

    public com.digitald4.clicktracker.proto.ClickTrackerProtos.Click getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_budget_Click_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_budget_Click_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022clicktracker.proto\022\006budget\"\217\001\n\005Click\022\n" +
      "\n\002id\030\001 \001(\005\022\013\n\003url\030\002 \001(\t\022\020\n\010recorded\030\003 \001(" +
      "\003\022\022\n\nip_address\030\004 \001(\t\022\027\n\017accept_language" +
      "\030\005 \001(\t\022\030\n\020request_language\030\006 \001(\t\022\024\n\014redi" +
      "rect_url\030\007 \001(\tB6\n com.digitald4.clicktra" +
      "cker.protoB\022ClickTrackerProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_budget_Click_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_budget_Click_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_budget_Click_descriptor,
        new java.lang.String[] { "Id", "Url", "Recorded", "IpAddress", "AcceptLanguage", "RequestLanguage", "RedirectUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
